---
version: '3'
services: 
 mydb: 
  image: mysql:5
  environment: 
   - MYSQL_ROOT_PASSWORD:priya
 apache: 
  image: httpd
  ports: 
   - 8000:80
  links: 
   - mydb:mysql
 php: 
  image: php:7.2-apache
  links: 
   - mydb:mysql
   - apache:httpd







...
