---
version: '3'
services: 
 hub: 
  image: selenium/hub
  ports: 
   - 4444:4444
 firefox:
  image: selenium/node-firefox-debug
  ports: 
   - 5901:5900
  environment: 
   HUB_HOST: hub
  links: 
   - hub:selenium
 chrome: 
  image: selenium/node-chrome-debug
  ports: 
   - 5902:5900
  links: 
   - hub:selenium








...
